server:
  port: 9501

spring:
  application:
    name: microcloud-zuul-gateway


eureka:
  client:
    register-with-eureka: false
    service-url:
      defaultZone: http://admin:enjoy@eureka1:7001/eureka,http://admin:enjoy@eureka2:7002/eureka,http://admin:enjoy@eureka3:7003/eureka
zuul:
  routes:
    #microcloud-provider-users: /users-proxy/**
    users:
      path: /users-proxy/**
      serviceId: microcloud-provider-users
    users2:
      path: /users2-proxy/**
      url: http://localhost:8090/
    product:
      path: /product-proxy/**
      serviceId: microcloud-provider-product
  ignored-services:
    "*"
  prefix: "/enjoy-api" #一旦设置了公共前缀，所以的访问路径都要在前面加上前缀 http://localhost:9501/enjoy-api/users-proxy/users/get/1
